### ISSUE TITLE
Dans la section static data, la current position évolue; 

### ISSUE THREAD

**Issue by VHR0707** [Skall34/FlightRecorder#13]
Empêcher la textbox "current position" de bouger. 
Elle évolue pendant le vol en fonction des aéroports qu'on survole :) Ca ne va pas;

Renommer le label en "Start Position"

**Comment by Skall34** [comment]
The start airport is in the start field of the flight summary.
The current position always gives the nearest airport. Eventually, we could move it into the dynamic data area ?

**Comment by VHR0707** [comment]
Pourquoi en anglais ?? Tu te crois au boulot ?? :) :) :)
Très perturbant de voir l'aéroport que tu survol s'afficher .... 
Le pb de start airport, c'est qu'il ne s'affiche que au démarrage. Du coup, on ne peut pas checker le fret avant.

Ou ne pas l'afficher, mais prendre les infos quand même pour afficher le frêt au début ?

**Comment by VHR0707** [comment]
Done avec #19
