### ISSUE TITLE
Vérifier immat et pilote non vide avant démarrage de l'acars

### ISSUE THREAD

**Issue by VHR0707** [Skall34/FlightRecorder#15]
Du coup, il faudra peut-être ? modifier la structure de l'acars.
C'est à dire lancer l'enregistrement avec un click bouton, ce qui permettra de faire des contrôles avant lancement de l'enregistrement.

Sinon, le faire sur le click du  submit vol, pour garder le démarrage auto, et bloquer l'envoi si contrôles NOK.

**Comment by VHR0707** [comment]
Après discussion on garde le démarrage auto, et on fait le check sur le bouton submit

**Comment by Skall34** [comment]
ok, in progress do checks before save

**Comment by Skall34** [comment]
Callsign can't be empty.
Callsign shall be formed by SKY followed by 4 digits.
mission can't be empty.
plane immat can't be empty.
changed plane immat combobox style to dropdownlist (non editable)
changed mission combobox style to dropdownlist (non editable)
changed note combobox style to dropdownlist (non editable)
