### ISSUE TITLE
Au changement de la combo immat, aller recharger le libellé.

### ISSUE THREAD

**Issue by VHR0707** [Skall34/FlightRecorder#16]

**Comment by VHR0707** [comment]
Pas d'intérêt d'aller récupérer cette donnée du simu.
Le libellé dans le fichier JSON suffit. Donc à lire au changement de la combo.

**Comment by Skall34** [comment]
ok. J'ai quand même gardé dans une trace quel avion etait chargé dans le simu

**Comment by Skall34** [comment]
done
