### ISSUE TITLE
les champs ICAO Depart et ICAO arrivée sont parfois vide

### ISSUE THREAD

**Issue by VHR0707** [Skall34/FlightRecorder#18]
Voir image

![Capture d'écran 2024-03-09 100124](https://github.com/Skall34/FlightRecorder/assets/70477313/4bdfab5a-99fa-4a17-9d2d-d4f412f25f01)

**Comment by VHR0707** [comment]
Commentaire de Bruno ce matin:
en fait, les points de départ et d'arrivée ne se sont pas affichés dans l'Acars, à aucun moment

**Comment by Skall34** [comment]
les logs devraient aider peut-être.

**Comment by Skall34** [comment]
a voir si ça le fera encore avec la nouvelle version. Le pb est potentiellement corrigé.
J'ai désactivé la connexion au simulateur tant que les données d'aéroport, vol et avions ne sont pas chargées.
(le chargement est asynchrone).

**Comment by VHR0707** [comment]
Oui, je suis d'accord. A surveiller

**Comment by VHR0707** [comment]
Je ferme. Plus reproduit depuis version 2.0.0.2. Grisage des labels
