### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by VHR0707** [Skall34/FlightRecorder#19]
Pascal,
A mon avis, il faut supprimer:
Toutes les dynamics data.

On a pas besoin de tout ça.

On a même plus besoin de la position de départ, puisqu'on ne fait plus de contrôle du frêt.

Pas sûr non plus d'avoir besoin d'un fuel refill
On doit faire le plein dans le simu. C'est plus réaliste.

**Comment by Skall34** [comment]
Je pense qu'on peut effectivement supprimer qq données dynamiques. 
J'aime bien, parce que ça permet d'être sur que l'ACARS reçoit bien les données venant du simu, mais au final, on
en a pas vraiment besoin.
Le fuel refill depuis l'acars, je le garderais quand même, ça permet, avec le fret de préparer l'avion sans passer par le simu,
dans x-plane notamment, c'est un peu pénible d'aller dans masses et centrage. Même si tu peux le faire si tu préfères passer par là.

**Comment by VHR0707** [comment]
Je viens seulement de voir ton commentaire sur le refill.
A rétablir si tu le veux
