### ISSUE TITLE
Système de réservation des avions à étudier

### ISSUE THREAD

**Issue by VHR0707** [Skall34/FlightRecorder#25]

**Comment by Skall34** [comment]
On sort du scope d'un simple "flight recorder".
A la limite, on pourrait développer d'autres fonctionnalités (comme celle-ci), mais il faudrait que ça soit dans un
autre onglet peut-être.
Par exemple, voir la liste des aeroport avec le fret dispo. chargement du fret depuis l'appli, re-fuel depuis l'appli, etc...

**Comment by VHR0707** [comment]
Il faut juste trouver un système pour que si un avion est utilisé, il ne soit pas listé dans l'acars.
Mais suis OK avec toi, c'est pas ACARS pur

**Comment by VHR0707** [comment]
Parfait avec solution actuelle
