### ISSUE TITLE
Transmettre le callsign du pilote de l'avion en vol

### ISSUE THREAD

**Issue by VHR0707** [Skall34/FlightRecorder#37]
Plutôt que de transmettre 0 ou 1, transmettre le callsign du pilote en vol
==> Modifier le remplissage de la combo immat pour filtrer sur autre que 0 plutôt que 1
==> On pourra faire une page dans le fichier de suivi des vols en direct.

**Comment by Skall34** [comment]
le callsign y est deja, dans la colonne J. mais par contre, on peut effectivement filtrer mieux ,et ajouter d'autres valeurs dans la colonne de reservation

**Comment by VHR0707** [comment]
Pas tout à fait d'accord.
Dans la colonne J, on a le dernier utilisateur de l'avion.
C'est positionné lors de l'import du vol dans la sheet.
Donc le vol est déjà terminé avec l'info de la colonne J. Il est tout à fait possible qu'un autre pilote soit en vol avec un avion dont le dernier utilisateur n'est pas lui.

**Comment by Skall34** [comment]
C'était le cas au début, avant la réservation, mais maintenant, la réalité, c'est que des que tu démarre un moteur, t'es le dernier pilote à avoir utilisé un avion, même si tu voles pas avec. Imagines que simplement tu déplaces l'avion en le démarrant, tu consommes du carbu ,et tu uses le moteur. Même si tu voles pas.
Après, cette valeur sera ré-écrite lors de la sauvegarde, mais à la limite, ce n'est même plus nécessaire.

**Comment by VHR0707** [comment]
OK, j'avais pas vu que tu réécrivais aussi callsign et localisation.
Ben c'est parfait alors
A clore je dirais.
Tu me dis quand t'es OK pour livrer cette version.
Elle est propre. J'ai fait 3 vols avec, RAS.
