### ISSUE TITLE
Libérer l'avion En vol sur fermeture de l'acars

### ISSUE THREAD

**Issue by VHR0707** [Skall34/FlightRecorder#38]
Si un vol est interrompu pour une raison ou une autre, l'avion reste considéré comme en vol.

**Comment by VHR0707** [comment]
1er test KO.
Il n'a pas le temps d'envoyer la requête au fichier car il se ferme.
Réfléchir.

**Comment by Skall34** [comment]
test de correction en cours.

**Comment by VHR0707** [comment]
Parfait pour moi.
Je clôture.
Prêt à être livré
