### ISSUE TITLE
automatiquement créer un bug dans github.

### ISSUE THREAD

**Issue by Skall34** [Skall34/FlightRecorder#43]
permettre à un utilisateur d'envoyer un probleme, en ajoutant un fichier attaché.

**Comment by Skall34** [comment]
fait, avec un menu contextuel dans l'appli : "clic-droit => submit bug".

**Comment by VHR0707** [comment]
Ne fonctionne pas de chez moi.

**Comment by Skall34** [comment]
problem was that personnal access token was deleted (why ? ) changed that to get the token from the sheet.
(added a new query). now we can create a new token without delivering a new acars version.

**Comment by Skall34** [comment]
done
