### ISSUE TITLE
SKY3434 problem : test issue from acars

### ISSUE THREAD

**Issue by Skall34** [Skall34/FlightRecorder#47]
Describe the problem:

==================
Log starts here 
================
20:40:48 : 
20:40:49 : .ctor in Form1.cs:72 : Starting flightrecorder
20:40:49 : .ctor in Form1.cs:91 : Version : 0.0.0.0
20:40:49 : .ctor in Form1.cs:101 : start loading airports database
20:40:49 : MoveNext in Aeroport.cs:124 : Fechting airport informations from server
20:40:49 : .ctor in Form1.cs:103 : start loading planes and missions
20:40:49 : .ctor in Form1.cs:107 : initialize the connection to the simulator
20:40:50 : .ctor in Form1.cs:143 : update form status
20:40:52 : TimerConnection_Tick in Form1.cs:278 : Still waiting for data before connecting to simulator
20:40:54 : TimerConnection_Tick in Form1.cs:278 : Still waiting for data before connecting to simulator
20:40:54 : MoveNext in Form1.cs:190 : done loading planes and missions
20:41:03 : TimerConnection_Tick in Form1.cs:278 : Still waiting for data before connecting to simulator
20:41:03 : MoveNext in Form1.cs:213 : Reading static values
20:41:03 : MoveNext in Form1.cs:164 : done loading airports database
20:41:03 : TimerConnection_Tick in Form1.cs:263 : Connected to simulator
20:41:03 : MoveNext in Form1.cs:213 : Reading static values
20:41:03 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:03 : MoveNext in Form1.cs:213 : Reading static values
20:41:03 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:03 : MoveNext in Form1.cs:213 : Reading static values
20:41:03 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:03 : MoveNext in Form1.cs:213 : Reading static values
20:41:03 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:03 : MoveNext in Form1.cs:213 : Reading static values
20:41:03 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:03 : MoveNext in Form1.cs:213 : Reading static values
20:41:03 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:03 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:04 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:04 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:05 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:05 : MoveNext in Form1.cs:213 : Reading static values
20:41:06 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes
20:41:06 : MoveNext in Form1.cs:213 : Reading static values
20:41:06 : MoveNext in Form1.cs:247 : Simulator aircraft loaded : Bell 407 Blue Stripes

**Comment by VHR0707** [comment]
Génial !
